/* ===========================================================================
   ERP INDUSTRIAL - schema Firebird 5

   Convencao de nomes usada pelo mapeador (ver Infra.Mapping.pas):
     tabela  -> registrada explicitamente na Infra
     coluna  -> nome da PROPRIEDADE da entidade, em maiusculas
     chave   -> sempre ID, alimentada por um GENERATOR

   Tipos:
     Currency (Delphi) -> NUMERIC(15,4)
     Double            -> DOUBLE PRECISION
     TDateTime         -> TIMESTAMP
     enumerado         -> VARCHAR(20) com o nome RTTI (ex.: 'spConfirmado')
     Boolean           -> BOOLEAN (nativo desde o Firebird 3)

   Rode com:  isql -i bd/schema.sql
   ou pelo proprio sistema:  GestaoComercial.exe --dbcriar
   =========================================================================== */

/* ------------------------------------------------------------- GENERATORS */
CREATE SEQUENCE GEN_CLIENTES_ID;
CREATE SEQUENCE GEN_PRODUTOS_ID;
CREATE SEQUENCE GEN_PEDIDOS_ID;
CREATE SEQUENCE GEN_PEDIDO_ITENS_ID;
CREATE SEQUENCE GEN_MOVIMENTOS_ID;
CREATE SEQUENCE GEN_PAGAMENTOS_ID;
CREATE SEQUENCE GEN_CENTROS_ID;
CREATE SEQUENCE GEN_ESTRUTURA_ID;
CREATE SEQUENCE GEN_ROTEIRO_ID;
CREATE SEQUENCE GEN_ORDENS_ID;
CREATE SEQUENCE GEN_OP_COMPONENTES_ID;
CREATE SEQUENCE GEN_OP_OPERACOES_ID;
CREATE SEQUENCE GEN_OP_APONTAMENTOS_ID;

/* -------------------------------------------------------------- CADASTROS */

CREATE TABLE CLIENTES (
  ID             INTEGER       NOT NULL,
  NOME           VARCHAR(80)   NOT NULL,
  DOCUMENTO      VARCHAR(20),
  EMAIL          VARCHAR(120),
  TELEFONE       VARCHAR(20),
  CIDADE         VARCHAR(60),
  UF             VARCHAR(2),
  CATEGORIA      VARCHAR(20)   DEFAULT 'ccComum' NOT NULL,
  LIMITECREDITO  NUMERIC(15,4) DEFAULT 0 NOT NULL,
  ATIVO          BOOLEAN       DEFAULT TRUE NOT NULL,
  CRIADOEM       TIMESTAMP,
  ATUALIZADOEM   TIMESTAMP,
  CONSTRAINT PK_CLIENTES PRIMARY KEY (ID)
);

CREATE TABLE PRODUTOS (
  ID             INTEGER       NOT NULL,
  CODIGO         VARCHAR(20)   NOT NULL,
  DESCRICAO      VARCHAR(100)  NOT NULL,
  CATEGORIA      VARCHAR(40),
  PRECO          NUMERIC(15,4) DEFAULT 0 NOT NULL,
  ESTOQUE        INTEGER       DEFAULT 0 NOT NULL,
  ESTOQUEMINIMO  INTEGER       DEFAULT 0 NOT NULL,
  ATIVO          BOOLEAN       DEFAULT TRUE NOT NULL,
  TIPO           VARCHAR(20)   DEFAULT 'tpRevenda' NOT NULL,
  UNIDADE        VARCHAR(6)    DEFAULT 'UN' NOT NULL,
  CUSTOMEDIO     NUMERIC(15,4) DEFAULT 0 NOT NULL,
  LEADTIMEDIAS   INTEGER       DEFAULT 0 NOT NULL,
  LOTEMINIMO     INTEGER       DEFAULT 1 NOT NULL,
  CRIADOEM       TIMESTAMP,
  ATUALIZADOEM   TIMESTAMP,
  CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID),
  CONSTRAINT UQ_PRODUTOS_CODIGO UNIQUE (CODIGO),
  CONSTRAINT CK_PRODUTOS_ESTOQUE CHECK (ESTOQUE >= 0)
);

CREATE TABLE CENTROS_TRABALHO (
  ID                 INTEGER       NOT NULL,
  CODIGO             VARCHAR(15)   NOT NULL,
  DESCRICAO          VARCHAR(60)   NOT NULL,
  CAPACIDADEHORASDIA DOUBLE PRECISION DEFAULT 8 NOT NULL,
  CUSTOHORA          NUMERIC(15,4) DEFAULT 0 NOT NULL,
  ATIVO              BOOLEAN       DEFAULT TRUE NOT NULL,
  CRIADOEM           TIMESTAMP,
  ATUALIZADOEM       TIMESTAMP,
  CONSTRAINT PK_CENTROS PRIMARY KEY (ID),
  CONSTRAINT UQ_CENTROS_CODIGO UNIQUE (CODIGO)
);

/* ------------------------------------------------------- ENGENHARIA (PCP) */

/* Estrutura de produto (BOM). Uma linha = "o pai leva N do componente".
   A UNIQUE evita a mesma dupla duas vezes; o CHECK evita item que leva
   a si mesmo (ciclo de nivel 1 - os demais o servico detecta). */
CREATE TABLE ESTRUTURA_ITENS (
  ID                  INTEGER          NOT NULL,
  PRODUTOPAIID        INTEGER          NOT NULL,
  COMPONENTEID        INTEGER          NOT NULL,
  CODIGOCOMPONENTE    VARCHAR(20),
  DESCRICAOCOMPONENTE VARCHAR(100),
  QUANTIDADE          DOUBLE PRECISION DEFAULT 1 NOT NULL,
  PERDAPERCENTUAL     DOUBLE PRECISION DEFAULT 0 NOT NULL,
  SEQUENCIA           INTEGER          DEFAULT 10 NOT NULL,
  CRIADOEM            TIMESTAMP,
  ATUALIZADOEM        TIMESTAMP,
  CONSTRAINT PK_ESTRUTURA PRIMARY KEY (ID),
  CONSTRAINT UQ_ESTRUTURA UNIQUE (PRODUTOPAIID, COMPONENTEID),
  CONSTRAINT CK_ESTRUTURA_CICLO CHECK (PRODUTOPAIID <> COMPONENTEID),
  CONSTRAINT CK_ESTRUTURA_QTD CHECK (QUANTIDADE > 0),
  CONSTRAINT FK_ESTRUTURA_PAI FOREIGN KEY (PRODUTOPAIID)
    REFERENCES PRODUTOS (ID),
  CONSTRAINT FK_ESTRUTURA_COMP FOREIGN KEY (COMPONENTEID)
    REFERENCES PRODUTOS (ID)
);

CREATE TABLE ROTEIRO_OPERACOES (
  ID               INTEGER          NOT NULL,
  PRODUTOID        INTEGER          NOT NULL,
  SEQUENCIA        INTEGER          NOT NULL,
  DESCRICAO        VARCHAR(60)      NOT NULL,
  CENTROID         INTEGER          NOT NULL,
  CODIGOCENTRO     VARCHAR(15),
  TEMPOSETUPMIN    DOUBLE PRECISION DEFAULT 0 NOT NULL,
  TEMPOUNITARIOMIN DOUBLE PRECISION DEFAULT 0 NOT NULL,
  CRIADOEM         TIMESTAMP,
  ATUALIZADOEM     TIMESTAMP,
  CONSTRAINT PK_ROTEIRO PRIMARY KEY (ID),
  CONSTRAINT UQ_ROTEIRO UNIQUE (PRODUTOID, SEQUENCIA),
  CONSTRAINT FK_ROTEIRO_PRODUTO FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS (ID),
  CONSTRAINT FK_ROTEIRO_CENTRO FOREIGN KEY (CENTROID)
    REFERENCES CENTROS_TRABALHO (ID)
);

/* ------------------------------------------------------------ VENDAS */

CREATE TABLE PEDIDOS (
  ID                INTEGER       NOT NULL,
  NUMERO            VARCHAR(15)   NOT NULL,
  CLIENTEID         INTEGER       NOT NULL,
  NOMECLIENTE       VARCHAR(80),
  STATUS            VARCHAR(20)   DEFAULT 'spRascunho' NOT NULL,
  FORMAPAGAMENTO    VARCHAR(20)   DEFAULT 'fpPix' NOT NULL,
  OBSERVACAO        VARCHAR(200),
  FRETE             NUMERIC(15,4) DEFAULT 0 NOT NULL,
  DESCONTONEGOCIADO NUMERIC(15,4) DEFAULT 0 NOT NULL,
  DATACONFIRMACAO   TIMESTAMP,
  DATAFECHAMENTO    TIMESTAMP,
  CRIADOEM          TIMESTAMP,
  ATUALIZADOEM      TIMESTAMP,
  CONSTRAINT PK_PEDIDOS PRIMARY KEY (ID),
  CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTEID) REFERENCES CLIENTES (ID)
);

/* ON DELETE CASCADE: o item nao existe sem o pedido (agregado). */
CREATE TABLE PEDIDO_ITENS (
  ID                 INTEGER          NOT NULL,
  PEDIDOID           INTEGER          NOT NULL,
  PRODUTOID          INTEGER          NOT NULL,
  CODIGOPRODUTO      VARCHAR(20),
  DESCRICAOPRODUTO   VARCHAR(100),
  QUANTIDADE         INTEGER          DEFAULT 1 NOT NULL,
  PRECOUNITARIO      NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  DESCONTOPERCENTUAL DOUBLE PRECISION DEFAULT 0 NOT NULL,
  CRIADOEM           TIMESTAMP,
  ATUALIZADOEM       TIMESTAMP,
  CONSTRAINT PK_PEDIDO_ITENS PRIMARY KEY (ID),
  CONSTRAINT FK_ITENS_PEDIDO FOREIGN KEY (PEDIDOID)
    REFERENCES PEDIDOS (ID) ON DELETE CASCADE
);

CREATE TABLE PAGAMENTOS (
  ID           INTEGER       NOT NULL,
  PEDIDOID     INTEGER       NOT NULL,
  VALOR        NUMERIC(15,4) DEFAULT 0 NOT NULL,
  FORMA        VARCHAR(20)   DEFAULT 'fpPix' NOT NULL,
  AUTORIZADO   BOOLEAN       DEFAULT FALSE NOT NULL,
  AUTORIZACAO  VARCHAR(60),
  CRIADOEM     TIMESTAMP,
  ATUALIZADOEM TIMESTAMP,
  CONSTRAINT PK_PAGAMENTOS PRIMARY KEY (ID)
);

/* -------------------------------------------------- ORDENS DE PRODUCAO */

CREATE TABLE ORDENS_PRODUCAO (
  ID                       INTEGER          NOT NULL,
  NUMERO                   VARCHAR(15)      NOT NULL,
  PRODUTOID                INTEGER          NOT NULL,
  CODIGOPRODUTO            VARCHAR(20),
  DESCRICAOPRODUTO         VARCHAR(100),
  QUANTIDADEPLANEJADA      DOUBLE PRECISION DEFAULT 0 NOT NULL,
  QUANTIDADEPRODUZIDA      DOUBLE PRECISION DEFAULT 0 NOT NULL,
  QUANTIDADEREFUGADA       DOUBLE PRECISION DEFAULT 0 NOT NULL,
  STATUS                   VARCHAR(20)      DEFAULT 'opPlanejada' NOT NULL,
  DATAPREVISTA             TIMESTAMP,
  DATAINICIO               TIMESTAMP,
  DATAFIM                  TIMESTAMP,
  CUSTOMATERIALPREVISTO    NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  CUSTOMATERIALREAL        NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  CUSTOOPERACIONALPREVISTO NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  CUSTOOPERACIONALREAL     NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  PEDIDOORIGEMID           INTEGER          DEFAULT 0 NOT NULL,
  OBSERVACAO               VARCHAR(200),
  CRIADOEM                 TIMESTAMP,
  ATUALIZADOEM             TIMESTAMP,
  CONSTRAINT PK_ORDENS PRIMARY KEY (ID),
  CONSTRAINT UQ_ORDENS_NUMERO UNIQUE (NUMERO),
  CONSTRAINT FK_ORDENS_PRODUTO FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS (ID)
);

/* A lista de material CONGELADA da ordem. */
CREATE TABLE OP_COMPONENTES (
  ID                   INTEGER          NOT NULL,
  ORDEMID              INTEGER          NOT NULL,
  PRODUTOID            INTEGER          NOT NULL,
  CODIGOPRODUTO        VARCHAR(20),
  DESCRICAOPRODUTO     VARCHAR(100),
  QUANTIDADENECESSARIA DOUBLE PRECISION DEFAULT 0 NOT NULL,
  QUANTIDADECONSUMIDA  DOUBLE PRECISION DEFAULT 0 NOT NULL,
  CUSTOUNITARIO        NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  CRIADOEM             TIMESTAMP,
  ATUALIZADOEM         TIMESTAMP,
  CONSTRAINT PK_OP_COMPONENTES PRIMARY KEY (ID),
  CONSTRAINT FK_OPCOMP_ORDEM FOREIGN KEY (ORDEMID)
    REFERENCES ORDENS_PRODUCAO (ID) ON DELETE CASCADE
);

/* O roteiro CONGELADO da ordem, com o realizado. */
CREATE TABLE OP_OPERACOES (
  ID                INTEGER          NOT NULL,
  ORDEMID           INTEGER          NOT NULL,
  SEQUENCIA         INTEGER          NOT NULL,
  DESCRICAO         VARCHAR(60),
  CENTROID          INTEGER          NOT NULL,
  CODIGOCENTRO      VARCHAR(15),
  TEMPOPREVISTOMIN  DOUBLE PRECISION DEFAULT 0 NOT NULL,
  TEMPOREALIZADOMIN DOUBLE PRECISION DEFAULT 0 NOT NULL,
  QUANTIDADEBOA     DOUBLE PRECISION DEFAULT 0 NOT NULL,
  QUANTIDADEREFUGO  DOUBLE PRECISION DEFAULT 0 NOT NULL,
  CUSTOHORA         NUMERIC(15,4)    DEFAULT 0 NOT NULL,
  STATUS            VARCHAR(20)      DEFAULT 'soPendente' NOT NULL,
  CRIADOEM          TIMESTAMP,
  ATUALIZADOEM      TIMESTAMP,
  CONSTRAINT PK_OP_OPERACOES PRIMARY KEY (ID),
  CONSTRAINT FK_OPOPER_ORDEM FOREIGN KEY (ORDEMID)
    REFERENCES ORDENS_PRODUCAO (ID) ON DELETE CASCADE
);

CREATE TABLE OP_APONTAMENTOS (
  ID                INTEGER          NOT NULL,
  ORDEMID           INTEGER          NOT NULL,
  SEQUENCIAOPERACAO INTEGER          NOT NULL,
  QUANTIDADEBOA     DOUBLE PRECISION DEFAULT 0 NOT NULL,
  QUANTIDADEREFUGO  DOUBLE PRECISION DEFAULT 0 NOT NULL,
  TEMPOMINUTOS      DOUBLE PRECISION DEFAULT 0 NOT NULL,
  OPERADOR          VARCHAR(40),
  MOTIVOREFUGO      VARCHAR(60),
  CRIADOEM          TIMESTAMP,
  ATUALIZADOEM      TIMESTAMP,
  CONSTRAINT PK_OP_APONTAMENTOS PRIMARY KEY (ID),
  CONSTRAINT FK_OPAP_ORDEM FOREIGN KEY (ORDEMID)
    REFERENCES ORDENS_PRODUCAO (ID) ON DELETE CASCADE
);

/* ------------------------------------------------------------- ESTOQUE */

/* Livro razao do estoque: so cresce, nunca se altera uma linha antiga.
   Sem FK para PRODUTOS de proposito: o historico sobrevive ao cadastro. */
CREATE TABLE MOVIMENTOS_ESTOQUE (
  ID               INTEGER       NOT NULL,
  PRODUTOID        INTEGER       NOT NULL,
  CODIGOPRODUTO    VARCHAR(20),
  TIPO             VARCHAR(20)   NOT NULL,
  QUANTIDADE       INTEGER       DEFAULT 0 NOT NULL,
  SALDORESULTANTE  INTEGER       DEFAULT 0 NOT NULL,
  MOTIVO           VARCHAR(80),
  PEDIDOID         INTEGER       DEFAULT 0 NOT NULL,
  ORDEMPRODUCAOID  INTEGER       DEFAULT 0 NOT NULL,
  CUSTOUNITARIO    NUMERIC(15,4) DEFAULT 0 NOT NULL,
  CRIADOEM         TIMESTAMP,
  ATUALIZADOEM     TIMESTAMP,
  CONSTRAINT PK_MOVIMENTOS PRIMARY KEY (ID)
);

/* --------------------------------------------------------------- INDICES */
CREATE INDEX IX_PEDIDOS_CLIENTE     ON PEDIDOS (CLIENTEID);
CREATE INDEX IX_PEDIDOS_STATUS      ON PEDIDOS (STATUS);
CREATE INDEX IX_ITENS_PEDIDO        ON PEDIDO_ITENS (PEDIDOID);
CREATE INDEX IX_PAGAMENTOS_PEDIDO   ON PAGAMENTOS (PEDIDOID);
CREATE INDEX IX_MOV_PRODUTO         ON MOVIMENTOS_ESTOQUE (PRODUTOID);
CREATE INDEX IX_MOV_ORDEM           ON MOVIMENTOS_ESTOQUE (ORDEMPRODUCAOID);
CREATE INDEX IX_ESTRUTURA_PAI       ON ESTRUTURA_ITENS (PRODUTOPAIID);
CREATE INDEX IX_ESTRUTURA_COMP      ON ESTRUTURA_ITENS (COMPONENTEID);
CREATE INDEX IX_ROTEIRO_PRODUTO     ON ROTEIRO_OPERACOES (PRODUTOID);
CREATE INDEX IX_ORDENS_STATUS       ON ORDENS_PRODUCAO (STATUS);
CREATE INDEX IX_ORDENS_PRODUTO      ON ORDENS_PRODUCAO (PRODUTOID);
CREATE INDEX IX_OPCOMP_ORDEM        ON OP_COMPONENTES (ORDEMID);
CREATE INDEX IX_OPOPER_ORDEM        ON OP_OPERACOES (ORDEMID);
CREATE INDEX IX_OPAP_ORDEM          ON OP_APONTAMENTOS (ORDEMID);

/* ----------------------------------------------------------------- VIEWS */

CREATE VIEW VW_ESTOQUE_CRITICO (CODIGO, DESCRICAO, TIPO, ESTOQUE,
  ESTOQUEMINIMO, FALTA, VALOR_REPOSICAO) AS
SELECT P.CODIGO, P.DESCRICAO, P.TIPO, P.ESTOQUE, P.ESTOQUEMINIMO,
       P.ESTOQUEMINIMO - P.ESTOQUE,
       (P.ESTOQUEMINIMO - P.ESTOQUE) * P.CUSTOMEDIO
  FROM PRODUTOS P
 WHERE P.ATIVO = TRUE
   AND P.ESTOQUE < P.ESTOQUEMINIMO;

/* A MESMA explosao de estrutura que o Delphi faz recursivamente, aqui
   resolvida pelo banco com WITH RECURSIVE. Vale comparar os dois codigos:
   Domain.Producao.Services -> TServicoEngenharia.ExplodirRecursivo */
CREATE VIEW VW_ESTRUTURA_EXPLODIDA (RAIZ_ID, NIVEL, COMPONENTE_ID, CODIGO,
  DESCRICAO, TIPO, QUANTIDADE) AS
WITH RECURSIVE ARVORE (RAIZ_ID, NIVEL, COMPONENTE_ID, QUANTIDADE) AS (
  SELECT E.PRODUTOPAIID, 0, E.COMPONENTEID,
         E.QUANTIDADE / (1 - E.PERDAPERCENTUAL)
    FROM ESTRUTURA_ITENS E
  UNION ALL
  SELECT A.RAIZ_ID, A.NIVEL + 1, F.COMPONENTEID,
         A.QUANTIDADE * (F.QUANTIDADE / (1 - F.PERDAPERCENTUAL))
    FROM ARVORE A
    JOIN ESTRUTURA_ITENS F ON F.PRODUTOPAIID = A.COMPONENTE_ID
   WHERE A.NIVEL < 12
)
SELECT A.RAIZ_ID, A.NIVEL, A.COMPONENTE_ID, P.CODIGO, P.DESCRICAO, P.TIPO,
       A.QUANTIDADE
  FROM ARVORE A
  JOIN PRODUTOS P ON P.ID = A.COMPONENTE_ID;

/* Eficiencia por centro de trabalho: previsto x realizado nas OPs. */
CREATE VIEW VW_EFICIENCIA_CENTRO (CODIGOCENTRO, OPERACOES, TEMPO_PREVISTO,
  TEMPO_REALIZADO, EFICIENCIA) AS
SELECT O.CODIGOCENTRO, COUNT(*), SUM(O.TEMPOPREVISTOMIN),
       SUM(O.TEMPOREALIZADOMIN),
       CASE WHEN SUM(O.TEMPOREALIZADOMIN) > 0
            THEN SUM(O.TEMPOPREVISTOMIN) / SUM(O.TEMPOREALIZADOMIN)
            ELSE 0 END
  FROM OP_OPERACOES O
 WHERE O.TEMPOREALIZADOMIN > 0
 GROUP BY O.CODIGOCENTRO;
